### ISSUE TITLE
torch.cuda.empty_cache() raises RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by johndmendonca** [s3prl/s3prl#102]
So our lab has multiple GPUs available for usage but they are shared. Therefore if 'cuda:0' is in use I'll resort to 'cuda:1' for instance (`--device='cuda:1'`) . However, this raises an error here:
https://github.com/s3prl/s3prl/blob/08875941a2f6c9e73659f291e22dcedb88ab42ef/downstream/runner.py#L284

and here(if I comment the one above):

https://github.com/s3prl/s3prl/blob/08875941a2f6c9e73659f291e22dcedb88ab42ef/downstream/runner.py#L334

```
Traceback (most recent call last):????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 2/2 [00:34<00:00, 14.09s/it]
  File "run_downstream.py", line 136, in <module>
    main()
  File "run_downstream.py", line 131, in main
    eval(f'runner.{args.mode}')()
  File "/cfs/tmp/johnm/s3prl/downstream/runner.py", line 237, in train
    save_names += self.evaluate(split, global_step)
  File "/cfs/tmp/johnm/s3prl/downstream/runner.py", line 334, in evaluate
    torch.cuda.empty_cache()
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/torch/cuda/memory.py", line 87, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: out of memory
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/tqdm/std.py", line 1134, in __del__
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/tqdm/std.py", line 1281, in close
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/tqdm/std.py", line 1467, in display
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/tqdm/std.py", line 1137, in __repr__
  File "/afs/l2f/home/jmen/.local/lib/python3.6/site-packages/tqdm/std.py", line 1424, in format_dict
TypeError: 'NoneType' object is not iterable
```

I believe this is due to the default device for empty_cache being 'cuda:0', which in this case is being fully used: discussion [here](https://discuss.pytorch.org/t/out-of-memory-when-i-use-torch-cuda-empty-cache/57898). 

This is a simple experiment (mfcc+MLP) so I commented both lines, problem fixed.

**Comment by leo19941227** [comment]
Hi,

May I ask what is your pytorch version? And if there is a minimal reproducible script for this behavior?
Since after some investigation it seems this might be a [legacy issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/3016) of pytorch, but I am not sure is the above link is related to the issue here.
Thanks!

**Comment by leo19941227** [comment]
I fixed this issue at 64102b12227ed37d64d599bbdb47d390b904fbd1.

**Comment by johndmendonca** [comment]
I have torch 1.7.0
