### ISSUE TITLE
Error running IC intent classification

### ISSUE THREAD

**Issue by jasonppy** [s3prl/s3prl#424]
Hi,

Thanks for the great repo and consistent support!

when I ran intent classification with default parameters and any upstream models. I got the following error 
```
overall:   0%|                                                                                                                    | 0/200000 [00:00<?, ?it/s/pytorch/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
train:   0%|                                                                                                                         | 0/723 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/pyp/s3prl/s3prl/run_downstream.py", line 202, in <module>
    main()
  File "/home/pyp/s3prl/s3prl/run_downstream.py", line 198, in main
    eval(f'runner.{args.mode}')()
  File "/home/pyp/s3prl/s3prl/downstream/runner.py", line 238, in train
    (loss / gradient_accumulate_steps).backward()
  File "/home/pyp/miniconda3/envs/tf2/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/pyp/miniconda3/envs/tf2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
overall:   0%|                                                                                                                    | 0/200000 [00:04<?, ?it/s]
```
Can you provide some guidance on this issue? 

Thanks in advance!

**Comment by leo19941227** [comment]
Hi,

Can you list your s3prl version (commit has if editable install) and your torch version?

**Comment by jasonppy** [comment]
Thanks for the quick reply.

s3prl version: 0.3.1, torch version:1.10.0

**Comment by leo19941227** [comment]
Oh I remembered this issue.
I remember this is a bug of torch and is why I once set the torch != 1.10.0
I try to upgrade to torch==1.10.2 and it works.
Let me find if there is a related issue in the torch's issue page.

**Comment by leo19941227** [comment]
I can't find the related issue for now. But I believe upgrading torch will be a feasible solution.
The torch != 1.10.0 is now back in the main branch: d07a4e5bb4997f8edf6538bbd5b2804f6c017bc6
